### ISSUE TITLE
Add config file if not already present

### ISSUE THREAD

**Issue by spuddybike** [CLOSER-Cohorts/ced2arddigenerator#1]
A config file for setting up global values or other items we want to inject into the file would be useful.

- agency
- xml-lang
- input file name
- output file name
- Human readable name for dataset
- statistics - which to be output
- harmonised code lists

**Comment by spuddybike** [comment]
the current implementation requires that the application.properties is used - a config which is more user friendly would be better,

**Comment by spuddybike** [comment]
Example config lines

--agengy uk.iser.ukhls
--rename whim_s7
--ddilang en-GB
--stats max,min,mean,mode,valid,invalid,freq,stdev
--outputfile s7quest_closer.sav

**Comment by alkondrashov** [comment]
I propose the following format for the config file:

```
agengy=uk.iser.ukhls
rename=whim_s7
ddilang=en-GB
stats=max,min,mean,mode,valid,invalid,freq,stdev
outputfile=s7quest_closer.sav
```

**Comment by alkondrashov** [comment]
This is how we could pass the config in:

`java -jar target/ced2arddigenerator-jar-with-dependencies.jar -config config.txt`
