### ISSUE TITLE
AttributePair for excluded variables

### ISSUE THREAD

**Issue by spuddybike** [CLOSER-Cohorts/ced2arddigenerator#19]
Where a variable has had a variable statistic excluded:
The following should be added before VariableReference
   
 <r:UserAttributePair>
      <r:AttributeKey>extension:redaction-information</r:AttributeKey>
      <r:AttributeValue>xxxxxxxxxxxxxxxxxxxx</r:AttributeValue>
    </r:UserAttributePair>

It would be ideal if we could have something where

xxxxxxxx = [list of excluded stats:text]

This should be pulled directly from the excluded variable stats line on the config file

**Comment by spuddybike** [comment]
@HayleyMills does this make sense to you?

**Comment by HayleyMills** [comment]
@spuddybike Yes that makes sense, you are suggesting it automatically lists which stats have been excluded which you can then add text to? 

This may be handled separately but I would also think we need to be able to add this attribute pair to non-excluded stat variables? For example were there are stats, but they may not reflect the data that the user will receive (NSHD) or cases were additional info about how variables have been derived (ALSPAC) would like to be added.

**Comment by alkondrashov** [comment]
It should not be difficult to add an attribute pair to non-excluded stat.

@HayleyMills and @spuddybike what would be an example of key and value for that attribute?

**Comment by spuddybike** [comment]
working
